name: Release Mod

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew jar
      - name: Get Version
        run: grep mod_version gradle.properties | awk -F= '{ print $2 }' >> version.txt
      - name: Release to Github
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ success() }}
        with:
          files: build/libs/*.jar
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
